### ISSUE TITLE
Munin plugin?

### ISSUE THREAD

**Issue by sumpfralle** [systemli/mail-tls-helper#22]
Hello,

I intend to add a munin plugin for the visualization of the numbers of mail submitted by transport security ("plain", "onion" and "tls"). Maybe we can exchange some thoughts about that (before I head into the wrong/unwanted direction.

* The munin plugin would be called every five minutes - thus it would probably use the live mail log.
    * No additional complications like handling a state would arise. Just outputting the currently gathered mail counts would be sufficient.
* I think, we should keep the single-file structure of the code.
* maybe we should re-organice the argument handling:
    * allow separate actions (e.g. "update postmap", "send mail hints", "output statistics") - maybe even executed in a single run via [`nargs` in argparse](https://docs.python.org/3.5/library/argparse.html#nargs)
    * otherwise we would probably need to a add a magic "--print-statistics-and-exit" switch, that would complicate the processing code

Or do you have other ideas how to approach this?

**Comment by t2d** [comment]
I think this is a great idea. If you're using the live log, the graph will reset on every logrotate.  Are you okay with this?

I feel like the only part missing then is another way of output for the statistics. Apart from this you have to call the script with `--no-postfix-map --no-summary`. Why not just add `--print-statistics`?

**Comment by sumpfralle** [comment]
> If you're using the live log, the graph will reset on every logrotate. Are you okay with this?

Yes, this is no problem. The munin master will track the state.

> Why not just add --print-statistics?

Interesting! I will take a look ...

**Comment by doobry-systemli** [comment]
Thanks a lot @sumpfralle for all your work on mail-tls-helper. It's much appreciated!

>  If you're using the live log, the graph will reset on every logrotate. Are you okay with this?

In our [`check_postfix.py` Icinga/Nagios monitoring plugin](https://github.com/systemli/monitoring-plugins-systemli/blob/master/check_postfix.py), I implemented a different way to parse the `mail.log`: It takes a specified time range (last X days/hours/minutes) and uses a binary search to find all relevant log lines from `mail.log` (and `mail.log.1` if necessary).

My idea was to migrate `mail-tls-helper` to this (smarter and faster) parsing logic and a simple state file that stores the last processed log line. That way, we could run `mail-tls-helper` on its own, and would not have to run it as a logrotate script.
Regarding statistics, it would allow to run `mail-tls-helper` against an arbitrary time range and print statistics for that range.

I have this on my todo since some months. Unfortunately I'm too busy with other things and probably will not find time to do that anytime soon. Maybe you want to take a look :) No pushing intended, feel free to ignore the comment :wink:

**Comment by sumpfralle** [comment]
> I feel like the only part missing then is another way of output for the statistics. Apart from this you have to call the script with --no-postfix-map --no-summary. Why not just add --print-statistics?

Yes, indeed this turned out to be a quite non-invasive approach. See #23.

> My idea was to migrate mail-tls-helper to this (smarter and faster) parsing logic and a simple state file that stores the last processed log line.

The munin plugin could be easily adjusted to such a stateful behaviour, later on. Simply replace `DERIVE` with `GAUGE`.

> Maybe you want to take a look [..]

Personally I tend to prefer simplicity over performance (as long as it does not hurt). Thus by adding a stateful parser logic I would need to work against my taste :(
But thank you for sharing your thoughts!

**Comment by sumpfralle** [comment]
Closed by #23
